project:
  type: website
  output-dir: docs

website:
  title: "M.Menezes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



